### PR TITLE
docs: new docs app (#865) merge from CirclonGroup to Mindbridge

### PR DESCRIPTION
**Pull request by WillForrestMindBridge**
This is a rather large commit that was updated just a few days ago on the main CirclonGroup github repository.

Unfortunately, it's just a documentation update, giving a few new example projects.

If we want to compare other fixes in the future, we'll probably want these some 100+ files on par so we can see actual changes...

Then again, maybe we should skip this merge. Thoughts?

PS. Also very confused what our main branch is.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/CirclonGroup/angular-tree-component/blob/master/CONTRIBUTING.md#commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by shardyMBAI** [comment]
@SpencerPolk @sarajmanes 

OH boi - this looks correct to me but think you folks would be best for knowing if this breaks our stuff

**Review by shardyMBAI — COMMENTED** [review]
Going to deffer to @sarajmanes and @SpencerPolk

**Review by SpencerPolk — APPROVED** [review]
Looking through these files, I don't think this will break anything, since essentially all the updates are to the docs-app itself. In terms of whether or not we should add this into our branch, that somewhat depends on if we want to have our branch be something we could potentially push back up to master, or consider it a longterm fork. I know @sarajmanes mentioned there may be some benefit to the second option, since some of what this library does isn't useful to us and introduces inefficiencies.

If we're unsure though, I'd say merge it. It shouldn't do any harm, and I don't THINK it will actually impact the front-end memory usage. That would be something to maybe check though.

**Comment by WillForrestMindBridge** [comment]
Cool. I don't mind putting this in either.

Do I have to make a brand new branch for this? so that we can get copies to webpack?

**Comment by shardyMBAI** [comment]
Once merged you can follow our [maintaining a fork](https://mindbridge-ai.atlassian.net/wiki/spaces/FG/pages/1488027671/Forking+a+Repository#Maintaining-a-fork.) instructions

**Pull request merged**
