### PR TITLE
AIA-13908: Differentiate user selection events vs. constructed select…

### PR DESCRIPTION
**Pull request by stevensoncam**
This pull request is a required pre-req for pull request https://github.com/mindbridge-ai/squanto-web-audit/pull/6672
addressing multiple problems deselecting nodes in mb-tree

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/CirclonGroup/angular-tree-component/blob/master/CONTRIBUTING.md#commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by SpencerPolk — APPROVED** [review]
This change makes sense to me. I did find a couple of issues, but I think they're mb-tree issues rather than a problem with this branch. I'll leave those comments on the other PR.

**Review by WillForrestMindBridge — APPROVED** [review]
This makes sense to me, and will finally give us some event to respond to...

**Review by jdbwin — APPROVED** [review]
nice job, Cam! Helluva starter task 😅

**Review by srilathass — APPROVED** [review]
looks good

**Pull request merged**
